name: Deploy MediaFlow

on:
  push:
    branches: [main]
    paths:
      - "src/api/**"
      - "functions/**"
      - "src/worker/**"
      - ".github/workflows/deploy.yml"
  workflow_dispatch:

concurrency:
  group: mediaflow-deploy
  cancel-in-progress: true

env:
  API_APP: mf-api-1757550168
  FUNC_APP: mf-func-1757550168
  ACR_LOGIN_SERVER: acrmediaflow1757550168.azurecr.io

jobs:
  deploy-api:
    name: Web App (API)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy API
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.API_APP }}
          publish-profile: ${{ secrets.WEBAPP_PUBLISH_PROFILE }}
          package: src/api

  deploy-functions:
    name: Function App (blob → Service Bus)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Zip functions
        run: |
          cd functions
          zip -r ../functions.zip .
          cd ..
      - name: Deploy Functions
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.FUNC_APP }}
          publish-profile: ${{ secrets.FUNCAPP_PUBLISH_PROFILE }}
          package: functions.zip

  build-worker:
    name: Build & push worker image (ACR)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - name: Build & push image
        run: |
          set -e
          TAG="worker-${GITHUB_SHA::7}"
          docker build -f src/worker/Dockerfile -t "$ACR_LOGIN_SERVER/mediaflow-worker:$TAG" src/worker
          docker tag  "$ACR_LOGIN_SERVER/mediaflow-worker:$TAG" "$ACR_LOGIN_SERVER/mediaflow-worker:worker-ci"
          docker push "$ACR_LOGIN_SERVER/mediaflow-worker:$TAG"
          docker push "$ACR_LOGIN_SERVER/mediaflow-worker:worker-ci"
      - name: Next step (manual one-liner)
        run: |
          echo "Update the Container App to the new image with:" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`bash" >> $GITHUB_STEP_SUMMARY
          echo "az containerapp update -g rg-mediaflow-dev -n mf-worker-ca --image $ACR_LOGIN_SERVER/mediaflow-worker:worker-ci" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
